[package]
name = "silo-vault"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
silo-core = { path = "../silo-core" }
silo-markdown = { path = "../silo-markdown" }
serde = { workspace = true }
serde_yaml = { workspace = true }
serde_json = "1"
directories = "5"
thiserror = { workspace = true }
tempfile = { workspace = true }
